[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true
panic = "abort"

[workspace]
members = [
  "r6502",
  "r6502config",
  "r6502core",
  "r6502cpu",
  "r6502lib",
  "r6502ui",
  "r6502validation",
]
resolver = "2"
