#![allow(unused)]

type VduCode = (u8, &'static str, u8, &'static str);

const VDU_CODES: [VduCode; 33] = [
    (0, "@", 0, "Does nothing"),
    (1, "A", 1, "Send next character to printer only"),
    (2, "B", 0, "Enable printer"),
    (3, "C", 0, "Disable printer"),
    (4, "D", 0, "Write text at text cursor"),
    (5, "E", 0, "Write text at graphics cursor"),
    (6, "F", 0, "Enable VDU drivers"),
    (7, "G", 0, "Make short beep (BEL)"),
    (8, "H", 0, "Move cursor back one character"),
    (9, "I", 0, "Move cursor forward one character"),
    (10, "J", 0, "Move cursor down one line"),
    (11, "K", 0, "Move cursor up one line"),
    (12, "L", 0, "Clear text area"),
    (13, "M", 0, "Carriage return"),
    (14, "N", 0, "Paged mode on"),
    (15, "O", 0, "Paped mode off"),
    (16, "P", 0, "Clear graphics area"),
    (17, "Q", 1, "Define text colour"),
    (18, "R", 2, "Define graphics colour"),
    (19, "S", 5, "Define logical colour"),
    (20, "T", 0, "Restore default logical colours"),
    (21, "U", 0, "Disable VDU drivers or delete input line"),
    (22, "V", 1, "Select screen MODE"),
    (
        23,
        "W",
        9,
        "Re-program display character + various other fn's",
    ),
    (24, "X", 8, "Define graphics window"),
    (25, "Y", 5, "PLOT k,x,y"),
    (26, "Z", 0, "Restore default windows"),
    (27, "[", 0, "ESCAPE value"),
    (28, "\\", 4, "Define text window"),
    (29, "]", 4, "Define graphics origin"),
    (30, "^", 0, "Home text cursor to top left of window"),
    (31, "_", 2, "Move text cursor to x, y"),
    (127, "del", 0, "Backspace and delete"),
];
