[package]
name = "r6502"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
clap-num = "1.2.0"
cursive = "0.21.1"
iter_mod = "0.1.0"
r6502lib = { path = "../r6502lib" }
